### ISSUE TITLE
Can App subscribe to an address like a device?

### ISSUE THREAD

**Issue by kcjian** [NordicSemiconductor/Android-nRF-Mesh-Library#165]
**Is your feature request related to a problem? Please describe.**
When my App accesses the network, I want to receive the publish information of the device. I want to ask if the App can subscribe to an address?

**Describe alternatives you've considered**
Implementing this functionality through gateways and servers

**Comment by roshanrajaratnam** [comment]
@kcjian Are you saying that you want to get the publication settings that's currently set on a node?

**Comment by kcjian** [comment]
@roshanrajaratnam 
Like mutual subscriptions between devices, I want to subscribe to devices with my mobile phone.
For example, there are two sensors A and B. When the data of A changes, they will publish information to address 0xAAAA. When the data of B changes, they will publish information to address 0xBBBB. I want to subscribe to these two addresses (0xAAAA, 0xBBBB) with my mobile phone to receive these information.

**Comment by roshanrajaratnam** [comment]
Right, this is something you can do by setting a proxy filter on one of the nodes you are connected. You can turn on the white list filter on one of the nodes and then add the two addresses you wish to receive the data from. Also note that once you disconnect from the node you will lose the proxy filter settings because its per connection and is cleared upon disconnection by the node itself.

**Comment by kcjian** [comment]
I see. Thank you very much.

**Comment by roshanrajaratnam** [comment]
@kcjian Happy to help! I will close this issue and if have anymore questions about this please reopen again.
