### ISSUE TITLE
After import from json it should also save it to db

### ISSUE THREAD

**Issue by DomiR** [NordicSemiconductor/Android-nRF-Mesh-Library#193]
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/master/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/MeshManagerApi.java#L1053

We probably want to add `mMeshNetworkDb.updateNetwork(mMeshNetworkDao, mMeshNetwork);` there as well...

**Comment by roshanrajaratnam** [comment]
@DomiR Currently importing a new network will [insert](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/master/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/MeshManagerApi.java#L1052) the network straightaway instead of updating and I have also added a conflict strategy to replace old data if the network exists already.
