### ISSUE TITLE
How to recover from a lost connection after provisioning?

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [NordicSemiconductor/Android-nRF-Mesh-Library#492]
Dear @roshanrajaratnam,  

I would appreciate your expertise with the following situation:

After provisioning, a new node advertises itself with node identity, which is used to connect to the new node to configure it (assign keys etc.). 

Sometimes it happens that the first connection to the freshly provisioned node gets lost with error code 19 (REASON_TERMINATE_PEER_USER). 

--- 

**A little background information:**
The disconnect seems to be related to the firmware updating the connection parameters. Every time the connection gets lost, the firmware logs the following lines:
```
<t:     907173>, ble_softdevice_support.c,  104, Successfully updated connection parameters
<t:     933787>, proxy.c,  648, Disconnected
```
If the connection stays, those lines don't show up.

Android then logs:
```
D/BluetoothGatt( 5547): onClientConnectionState() - status=0 clientIf=21 device=DA:C4:DE:9A:C5:60
D/BluetoothGatt( 5547): onClientConnectionState() - status=19 clientIf=21 device=DA:C4:DE:9A:C5:60
D/BluetoothGatt( 5547): refresh() - device: DA:C4:DE:9A:C5:60
D/BluetoothGatt( 5547): close()
D/BluetoothGatt( 5547): unregisterApp() - mClientIf=21
V/MyMeshManager( 5547): onDeviceDisconnected. null, DA:C4:DE:9A:C5:60 Reason: REASON_TERMINATE_PEER_USER
```

The firmware is based on nRF5 SDK for Mesh 5.0.0 with nRF5 SDK 17.0.2 and Softdevice s132 7.3.0 running on a nRF52832. However, the same issue happens with a NCS (Zephyr) based firmware, making me believe that this is an issue at my Android app. What's interesting is that it seems to happen more frequently than more nodes there are in the mesh.

@roshanrajaratnam  Have you (or maybe one of your coworkers from the nRF5 SDK for Mesh team) ever seen something similar? Any ideas about the source of the disconnect and how to avoid it would be very much appreciated.

But even if the bug that causes the disconnect is fixed, it still could happen that the user walks out of range - i.e. a legitimate disconnect, in which case my app needs to be able to recover, so back to the original question... 

---

Once the initial connection to the freshly provisioned node is lost, the node is no longer advertising itself with node identity. Question now is, what's the best way to reconnect in this situation?

One approach would be to:
1. Scan for proxy nodes.
2. Connect to the first proxy node found.
3. Send a `ConfigNodeIdentitySet` message to the provisioned node to re-enable advertising with node identity.
4. Disconnect.
5. Scan, connect and resume configuring the node.

But there's another problem with this: If no other node has been provisioned yet, a fallback solution is needed. 

The simplest one would be to just connect using the BLE device (mac address) found while scanning for devices to provision.

The (potential) problem here is that the node's mac address could (theoretically) change. But the way the firmware is implemented, the mac address should stay constant. Also, my Android app does not supporting any third party devices, which lead to the idea to just always connect to a new node using the BLE device to set it up. Question now is, is this a bad idea? 

Beside the changing MAC address, do you see any other potential problems when connecting directly to the BLE device to configure a freshly provisioned node? 

The root cause is that the initial connection gets lost, which I haven't been able to find yet, so any advise on this one would be very much welcome as well.

Thanks for your help.

**Comment by roshanrajaratnam** [comment]
@FluffyBunniesTasteTheBest Let me answer the question regarding identifying a node after provisioning first. if the node is not advertising with node identify, you can still check for the network id. If you refer to the sample app, we scan and check if a node is advertising with node identity or network id. If your connection times out, you can still find a device using network identity and configure the device so you don't necessarily need the device address. I would like to stay out using a bluetooth address here because this is something out of the bluetooth mesh specification and from my point of view you should be able to configure device independent of it advertising a node identity. 

I have not seen this issue relating to connection parameters. What are the connection parameters you are requesting from the firmware side? On what Android version are you seeing this? A user walking out of range of a device is considered as a link loss which is invoked as a callback from our ble library. Therefore you can differentiate between a link loss and a normal disconnection due to an error.
